"""Configuration constants for code chunking."""

LANGUAGE_ALIASES = {
    "py": "python",
    "python": "python",
    "js": "javascript",
    "jsx": "javascript",
    "javascript": "javascript",
    "ts": "typescript",
    "tsx": "tsx",
    "typescript": "typescript",
    "c++": "cpp",
    "cc": "cpp",
    "cpp": "cpp",
    "cxx": "cpp",
    "h": "cpp",
    "hh": "cpp",
    "hpp": "cpp",
    "hxx": "cpp",
    "java": "java",
    "go": "go",
    "golang": "go",
    "rs": "rust",
    "rust": "rust",
}

CHUNK_NODE_KINDS = {
    "python": [
        "class_definition",
        "function_definition",
    ],
    "javascript": [
        "class_declaration",
        "function_declaration",
        "method_definition",
        "arrow_function",
        "lexical_declaration",
    ],
    "typescript": [
        "class_declaration",
        "function_declaration",
        "method_definition",
        "arrow_function",
        "lexical_declaration",
        "interface_declaration",
        "type_alias_declaration",
    ],
    "tsx": [
        "class_declaration",
        "function_declaration",
        "method_definition",
        "arrow_function",
        "lexical_declaration",
        "interface_declaration",
        "type_alias_declaration",
    ],
    "cpp": [
        "function_definition",
        "class_specifier",
        "struct_specifier",
        "namespace_definition",
        "template_declaration",
    ],
    "java": [
        "class_declaration",
        "interface_declaration",
        "method_declaration",
        "constructor_declaration",
    ],
    "go": [
        "function_declaration",
        "method_declaration",
        "type_declaration",
    ],
    "rust": [
        "function_item",
        "impl_item",
        "struct_item",
        "enum_item",
        "trait_item",
    ],
}

DEFINITION_KINDS = {
    "class_definition",
    "function_definition",
    "class_declaration",
    "function_declaration",
    "method_definition",
    "class_specifier",
    "struct_specifier",
    "namespace_definition",
    "template_declaration",
    "interface_declaration",
    "type_alias_declaration",
    "method_declaration",
    "constructor_declaration",
    "function_item",
    "impl_item",
    "struct_item",
    "enum_item",
    "trait_item",
}

JS_IMPORT_PATTERNS = [
    r"^\s*import\s+.*?\s+from\s+['\"]([^'\"]+)['\"]",
    r"^\s*import\s+['\"]([^'\"]+)['\"]",
    r"require\(['\"]([^'\"]+)['\"]\)",
]

IMPORT_PATTERNS = {
    "python": [
        r"^\s*import\s+([A-Za-z0-9_.,\s]+)",
        r"^\s*from\s+([A-Za-z0-9_.]+)\s+import\s+",
    ],
    "javascript": JS_IMPORT_PATTERNS,
    "typescript": JS_IMPORT_PATTERNS,
    "tsx": JS_IMPORT_PATTERNS,
    "java": [
        r"^\s*import\s+([A-Za-z0-9_.*]+);",
    ],
    "cpp": [
        r"^\s*#include\s+[<\"]([^>\"]+)[>\"]",
        r"^\s*using\s+namespace\s+([A-Za-z0-9_:]+);",
    ],
    "go": [
        r"^\s*import\s+\"([^\"]+)\"",
        r"^\s*\"([^\"]+)\"",
    ],
    "rust": [
        r"^\s*use\s+([^;]+);",
    ],
}

CALL_EXCLUDED_KEYWORDS = {
    "if",
    "for",
    "while",
    "switch",
    "catch",
    "return",
    "function",
    "def",
    "class",
    "new",
}

SYMBOL_EXCLUDED_KEYWORDS = {
    "and",
    "as",
    "async",
    "await",
    "break",
    "case",
    "catch",
    "class",
    "const",
    "continue",
    "def",
    "else",
    "except",
    "false",
    "finally",
    "for",
    "from",
    "func",
    "function",
    "if",
    "import",
    "in",
    "interface",
    "let",
    "new",
    "none",
    "null",
    "package",
    "pass",
    "private",
    "public",
    "return",
    "self",
    "static",
    "struct",
    "switch",
    "this",
    "throw",
    "true",
    "try",
    "type",
    "var",
    "while",
}
